% 计算Jacobian矩阵
% 2018/12/19
function [ J1,J ] = JacoJ( nodeC,elemN,ielem,nnode,s,t )
L = [s,t];%面积坐标
switch nnode
    case{3}
        J1 = [1 0 -1;0 1 -1];
        J = J1 ...
            * [ nodeC(elemN(ielem,1),1) nodeC(elemN(ielem,1),2) ...
            ; nodeC(elemN(ielem,2),1) nodeC(elemN(ielem,2),2) ...
            ; nodeC(elemN(ielem,3),1) nodeC(elemN(ielem,3),2)];%三角形用不到局部坐标，求导之后全是常数
    case{6}
        J1 = [ 4*L(1)-1 0 4*(L(1)+L(2))-3 4*L(2) -4*L(2) 4-8*L(1)-4*L(2) ; ...
              0 4*L(2)-1 4*(L(1)+L(2))-3 4*L(1) 4-4*L(1)-8*L(2) -4*L(1) ];
        J =  J1 * ...
            [ nodeC(elemN(ielem,1),1) nodeC(elemN(ielem,1),2) ...
            ; nodeC(elemN(ielem,2),1) nodeC(elemN(ielem,2),2) ...
            ; nodeC(elemN(ielem,3),1) nodeC(elemN(ielem,3),2) ...
            ; nodeC(elemN(ielem,4),1) nodeC(elemN(ielem,4),2) ...
            ; nodeC(elemN(ielem,5),1) nodeC(elemN(ielem,5),2) ...
            ; nodeC(elemN(ielem,6),1) nodeC(elemN(ielem,6),2)];
    otherwise
        disp('JacoJ ERROR!')
end
end


% xiezhuoyu
% mechanics_xzy@163.com